### PR TITLE
Add id property to PartialMember and PartialUser

### PR DESCRIPTION
**Pull request by verticalsync**
## Description

Add the user id property to PartialMember and PartialUser classes, do not know why they weren't there already.

### CODE REVIEW

**Comment by terrified9** [comment]
lgtm.

**Comment by AlexFlipnote** [comment]
Both PartialMember and PartialUser might not seem to have it on their main class, but they do have it due to:
- PartialMember and PartialUser uses PartialBase
- PartialBase uses Snowflake
- Snowflake is the base of Discord Snowflakes that handles `Snowflake.id` and `Snowflake.created_at`

You can think of it like a template for all Snowflake objects that Discord has to offer, so if all role/user/member/guild IDs get a new thing they all can do, I simply can change the `Snowflake` class to make all of them take advantage of it

Code_2024-03-24_23-08-32

**Comment by verticalsync** [comment]
Yeah, just realized this myself, sorry for wasting your time :P

**Comment by AlexFlipnote** [comment]
No all good, it was a genuine question and I appreciate it ❤️

**Pull request closed without merging**
